name: Build Android

on:
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  build-android-adhoc:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
      - name: Installing node
        uses: actions/setup-node@v1
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Building bundle
        run: |
          yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
      - name: Build android
        env:
          KEYSTORE_ALIAS_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_ALIAS_PASSPHRASE }}
          KEYSTORE_ALIAS: ${{ secrets.STAGING_KEYSTORE_ALIAS }}
          KEYSTORE_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_PASSPHRASE }}
        run: |
          export VERSION_CODE=${{ github.run_number }}
          export VERSION_NAME=1.0.${{ github.run_number }}
          echo ${{ secrets.STAGING_KEYSTORE }} | base64 --decode > android/app/staging.keystore
          cd android && ./gradlew -PversCode=$VERSION_CODE -PversName=$VERSION_NAME :app:assembleStaging
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: android/app/build/outputs/apk/staging/app-staging.apk