name: Build Android App PlayStore

on:
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  build-android-adhoc:
    runs-on: ubuntu-latest
    name: "Build Android app"

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Getting the repo
        uses: actions/checkout@v2

      # Install node
      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install React Native CLI, used to bundle the app
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli

      # Install Yarn dependencies
      - name: Install Yarn dependencies
        run: |
          yarn install

      - name: Make envfile Acceptation
        if: github.ref == 'refs/heads/main'
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ENDPOINT_TO_ENFORCE: ${{ secrets.ACC_ENDPOINT_TO_ENFORCE }}
          envkey_API_KEY: ${{ secrets.ACC_API_KEY }}
          envkey_RADAR_PUBLISHABLE_KEY: ${{ secrets.RADAR_PUBLISHABLE_KEY }}

      - name: Make envfile Development
        if: github.ref != 'refs/heads/main'
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ENDPOINT_TO_ENFORCE: ${{ secrets.DEV_ENDPOINT_TO_ENFORCE }}
          envkey_API_KEY: ${{ secrets.DEV_API_KEY }}
          envkey_RADAR_PUBLISHABLE_KEY: ${{ secrets.RADAR_PUBLISHABLE_KEY }}

      # Build Android app
      - name: Build Android
        env:
          KEYSTORE_ALIAS_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_ALIAS_PASSPHRASE }}
          KEYSTORE_ALIAS: ${{ secrets.STAGING_KEYSTORE_ALIAS }}
          KEYSTORE_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_PASSPHRASE }}
        run: |
          export VERSION_CODE=${{ github.run_number }}
          export VERSION_NAME=1.0.${{ github.run_number }}
          echo ${{ secrets.STAGING_KEYSTORE }} | base64 --decode > android/app/staging.keystore
          cd android && ./gradlew -PversCode=$VERSION_CODE -PversName=$VERSION_NAME bundleRelease

      # Upload app as Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 2
          name: android-app
          path: android/app/build/outputs/bundle/release/app-release.aab
    
      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.projectaccessibility
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: beta
          whatsNewDirectory: app-patchnotes/Android
          inAppUpdatePriority: 2
